### ISSUE TITLE
NmeaConverter_pi Crashes Opencpn

### ISSUE THREAD

**Issue by Zed222** [RooieDirk/NmeaConverter_pi#14]
OS = Ubuntu 18.04.2 LTS
OpenCPN=Version 4.8.8 Build 2018-11-06
NmeaConvert_pi = nmeaconverter_pi_1.0-1_amd64 compiled on the same machine as O.

Using convert C to F for temp ( $XXMTA, 9/5*$AIMTW5 + 32, F) with send after all updates variables checked.  

As soon as I start to playback a NMEA stream via VDR plugin or VDRplayer.py OpenCPN crashes. A look at the O logs does not produce any clues. 

As a side note I have compiled and used the Tactics plugin with the same nmea file with VDRplayer and O and Tactics run just fine

**Comment by RooieDirk** [comment]
You are using an ..MTW sence. Format according my info:
MTW - Mean Temperature of Water
 $--MTW,x.x,C*hh<CR><LF>
This sentence has only 2 fields available, the first one given the temp value  and the second just 'C' for 'Celsius'.
In your command sentense ($XXMTA, 9/5*$AIMTW5 + 32, F) ) You are requesting the 5th field of the MTW sentence, but that field does not exist.
Try again with $XXMTA, 9/5*$AIMTW1 + 32, F

**Comment by Zed222** [comment]
Used new formula provided above.. Still Crashed.

I removed the $Dummy entry  that came with NmeaConverter_pi install.

OpenCPN no longer crashes with NmeaConverter_pi enabled with a NMEA stream present..

And as provided for above $XXMTA, 9/5*$AIMTW1 + 32, F, is showing the "Air Temp" in F in Dasboard on O.
I can never thank the volunteers enough for all these wonderful tools..

Cheers

**Comment by rgleason** [comment]
Added to the wiki here. Can't loose these good examples!!!
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:plugins:logs:nmea_converter#convert_temperature_c_to_farenheit
