### ISSUE TITLE
More than 360 degree

### ISSUE THREAD

**Issue by spidgrou** [RooieDirk/NmeaConverter_pi#18]
Hi,
this sentence:
$WIMWD,($??MWV1+$??HDT1),T,,M,$??MWV3,N,,M
help me to find the true wind direction making a sum between true wind angle (MWV) and true heading (HDT)
All works fine until the sum of the two angles is bigger than 360.
I see that is impossible to put an 'IF' to remove 360 when the angle is more than 360.
Any other advice?
Thanks
Max

**Comment by rgleason** [comment]
Try to convert to RAD then back to DEG
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:plugins:logs:nmea_converter

Don't know if that will work, but it might.

**Comment by rgleason** [comment]
Here is something that might work.
["Comparing angles and working out the difference"](https://gamedev.stackexchange.com/questions/4467/comparing-angles-and-working-out-the-difference)

See the text and adapt it?
angle = 180 - abs(abs(a1 - a2) - 180);

**Comment by RooieDirk** [comment]
Would be nice if there was a Mod function, but there isn't one. However something like this should work as a homebrew mod function.
=( _Angle_ /360-INT( _Angle_ /360))*360

**Comment by spidgrou** [comment]
Guys,
Thanks for all your advice.
I will working on it and hopefully back with something that works. 

Max

**Comment by spidgrou** [comment]
@rgleason I work on your suggestion and I found the solution.

All data comes from Raymarine instrument with Nmea 0183.

here the two instruction to have on OpenCPN:
- True Heading
- True Wind Direction 0-359

$XXHDT,$??HDG1,T
$WIMWD,($??MWV1+$??HDT1)+ceil((-($??MWV1+$??HDT1))/360)*360,T,,M,$??MWV3,N,,M

It works very good.

Thanks to all of your for help and support I really appreciate.

Max

**Comment by rgleason** [comment]
Good!
So the formula to normalize the degrees to be between 0-360 is

ceil((-($??MWV1+$??HDT1))/360)*360

?

**Comment by spidgrou** [comment]
YES it is.

Thanks mate.

**Comment by rgleason** [comment]
Any chance of a screenshot ?

See
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:plugins:logs:nmea_converter#fix_greater_than_360_degrees_issue

**Comment by spidgrou** [comment]
Yes,
I can do it, but tomorrow. 
Tonight we have 0.0kt of wind :-O

Send an example.

![OpenCPN2](https://user-images.githubusercontent.com/42083306/58308073-a5787b80-7e54-11e9-9e25-c895095b6ae9.png)

**Comment by rgleason** [comment]
Thanks,  I added the screenshot, but it looks a little fuzzy.
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:plugins:logs:nmea_converter#normalize_degrees_to_less_than_360
Maybe a better one?

**Comment by spidgrou** [comment]
Hi,
here other two print screen.
I don't see them fuzzy, just light colors... anyway these are with strong colors.
Take a look if you like them.

Max
![OpenCPN4](https://user-images.githubusercontent.com/42083306/58449267-df03fc00-815e-11e9-888a-27449644f536.png)
![OpenCPN3](https://user-images.githubusercontent.com/42083306/58449282-ed521800-815e-11e9-8c3d-a8b86491100b.png)

**Comment by rgleason** [comment]
Thank you.  I realized I needed to crop to get the text to even begin to show. But it is better!
I think we'll keep both shots up.
Thank you again!

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:plugins:logs:nmea_converter#normalize_degrees_to_less_than_360

Mission accomplished.  Now I think you can close this Issue just below.
