### ISSUE TITLE
Doest not build

### ISSUE THREAD

**Issue by pa2wlt** [RooieDirk/NmeaConverter_pi#20]
Downloaded the sources into the OpenCPN sourcetree. Building a package fails due to the error below. Developing on Windows 10, Visual Studio 2017, wxWidgets 3.1.2, OpenCPN 5.0. Using **cmake -G "Visual Studio 15 2017" -T v141_xp ..**

> NmeaConverter_pi.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __thiscall wxEcEngine::SetTrigonometricMode(int)" (__im
> p_?SetTrigonometricMode@wxEcEngine@@QAEXH@Z) referenced in function __catch$?ShowPreferencesDialog@NmeaConverter_pi@@UAEXPAVwxWindow@@@Z$0 [C:\Users\myname\
> Sources\OpenCPN\plugins\NmeaConverter_pi\build\nmeaconverter_pi.vcxproj]
> C:\Users\myname\Sources\OpenCPN\plugins\NmeaConverter_pi\build\Debug\nmeaconverter_pi.dll : fatal error LNK1120: 1 unresolved externals [C:\Users\myname\Sou
> rces\OpenCPN\plugins\NmeaConverter_pi\build\nmeaconverter_pi.vcxproj]

**Comment by rgleason** [comment]
Werner,  I just made [my repos  master branch](https://github.com/rgleason/NmeaConverter_pi/commits/master)
match rooiedirk's master, using the following technique, which is not recommended if you are the primary repository with others contributing:
git branch -m master master.old     (rename master to master.old)
git fetch upstream master:master  (fetch master from upstream master)
git checkout master          (checkout the new master
git push origin +master   (force just the master branch)
git branch -d --force master.old  (delete the old branch)

And then used it locally and was able to build the plugin

>  CPack: Create package using NSIS
>   CPack: Install projects
>   CPack: - Install project: nmeaconverter_pi
>   CPack: Create package
>   CPack: - package: C:/Users/Rick/Documents/GitHub/NmeaConverter_pi/build/nmeaconverter_pi-1.0-win3
>   2.exe generated
> 
CMake needs an update to add "ov50" to the filename, also the travis file needs changing because it does not compile and needs an update to the current travis method of building.

When I run my ov50 branch I get

**Comment by pa2wlt** [comment]
Thx @rgleason  Not sure if I do follow what you mean by  

> Hi Sean,

Haven't heard from you a long time. Hope all is well. 
I spend the last few days to setup a Windows 10 computer, with a working development environment to be able to make changes in the plugins. That wasn't funny, though it works now.

My main focus in on calculation true wind, since my instruments don't do that. Thomas already did very good work on that in tactics_pi. The other thing I'd like to work on is to create an alarm for the rudder sensor. My (hydraulic) rudder is not stable and moving. Especially in very big waves, this is dangerous, since my ship can then start broaching instead of surfing. This mainly happens when the rudders moves, without noticing on time.

Obviously the one thing I have to do, is get that rudder fixed, which I will. Nevertheless, while being on in the open, 1000 nM or more from land, I would also like to anticipate on a moving rudder. Therefore I'd like to see if I can create that one in Watchdog.

I'll keep you update about the progress. It will take a while, since as said the TrueWind is the first one.

In case you have thought to share, please do so.

**Comment by rgleason** [comment]
Werner These are just comments for CI deployment.  Notice the green checks and red X"s in the list of commits?    for example click on the red X towards the top to see what build with CI  (appveyor and travis)
https://github.com/rgleason/NmeaConverter_pi/commits/master

Has nothing to do with your compiling, but notice appveyor (windows) does build with a green check.

**Comment by pa2wlt** [comment]
Thx @rgleason You're referring to the CI-tooling. Great. I reckon we wait now for @RooieDirk ?

**Comment by rgleason** [comment]
Werner, you should be able to build it locally from rooiedirk:master
I was able to do it.  Give it another try. If that does not work, git clone rooie's repos again and try it fresh.

**Comment by pa2wlt** [comment]
I will.

**Comment by pa2wlt** [comment]
I just did @rgleason, though no luck. Still an error while building  :-(

NmeaConverter_pi.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __thiscall wxEcEng
ine::SetTrigonometricMode(int)" (__imp_?SetTrigonometricMode@wxEcEngine@@QAEXH@Z) referenced in function __catch$?ShowP
referencesDialog@NmeaConverter_pi@@UAEXPAVwxWindow@@@Z$0 [C:\Users\myname\Sources\NmeaConverter_pi\build\nmeaconverter_
pi.vcxproj]
C:\Users\myname\Sources\NmeaConverter_pi\build\Debug\nmeaconverter_pi.dll : fatal error LNK1120: 1 unresolved externals
 [C:\Users\myname\Sources\NmeaConverter_pi\build\nmeaconverter_pi.vcxproj]

**Comment by rgleason** [comment]
So what did you do to set this up to build?
1. make a "build" directory?
2. add the current opencpn.lib 
Looks like you did that, but check the build directory yourself to find opencpn.lib.

What about using:
cmake -G "Visual Studio 15 2017" -T v141_xp ..
cmake --build . --config release
cpack      <--to package it.

**Comment by pa2wlt** [comment]
Thx again. Yes, all these things are in place, and indeed it builds other plugins properly. For this particular pluging, it all goes well including the cmake -G "Visual Studio 15 2017" -T v141_xp .. command.

When I then directly do 'cmake --build . --config release' it does proceed with these warnings:
2 x warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHs
33 x warning C4273: 'wxEcEngine::wxEcEngine': inconsistent dll linkage
5 x  warning LNK4217: locally defined symbol
though no error and 'cpack' then generates the install package correctly. I haven't functionally tested the nmea_converter, but it installs properly.

What I do normally (as with all other plugins) is:

> cmake --build .
> cmake --build . --config release
> cmake --build . --config release --target package

That 'cmake --build .' command generates the same warnings, though also a fatal error:

> NmeaConverter_pi.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __thiscall wxEcEng
> ine::SetTrigonometricMode(int)" (__imp_?SetTrigonometricMode@wxEcEngine@@QAEXH@Z) referenced in function __catch$?ShowP
> referencesDialog@NmeaConverter_pi@@UAEXPAVwxWindow@@@Z$0 [C:\Users\Werner\Sources\NmeaConverter_pi\build\nmeaconverter_
> pi.vcxproj]
> C:\Users\Werner\Sources\NmeaConverter_pi\build\Debug\nmeaconverter_pi.dll : fatal error LNK1120: 1 unresolved externals
>  [C:\Users\Werner\Sources\NmeaConverter_pi\build\nmeaconverter_pi.vcxproj]
>

**Comment by rgleason** [comment]
Yes it does build. See branch ov50
https://github.com/rgleason/NmeaConverter_pi/tree/ov50

Also please refer to releases
https://github.com/rgleason/NmeaConverter_pi/releases

See the commits here
https://github.com/rgleason/NmeaConverter_pi/commits/ov50

Notice the Green check?
Click on it, then pick Appveyor (builds Windows version) and Details.
You will see the appveyor console. Notice that it build successfully and deployed to github Releases.
Now click on artifacts where there should be a copy of the file created. --Well its been more than 6 months, so the file has been removed.

Appveyor built successfully, so use this repos and branch ov50 and build the same as appveyor.

Please close this Issue now.

**Comment by pa2wlt** [comment]
On my local Windows machine it did not build properly, and I gave up trying.

**Comment by rgleason** [comment]
pa2wlt  It occurs to me, are you using the newer package for opencpn files?
Take a look at one of the more current plugins  under appevor.yml 
https://github.com/rgleason/weather_routing_pi/blob/master/appveyor.yml
```
# Download and unzip wxwidgets
  # http://opencpn.navnux.org/build_deps/wxWidgets-3.1.2.7z - no longer available, replaced with below
  - ps: Start-FileDownload https://download.opencpn.org/s/E2p4nLDzeqx4SdX/download -FileName wxWidgets-3.1.2.7z
  - cmd: 7z x wxWidgets-3.1.2.7z -o%WXWIN% > null
```
