### ISSUE TITLE
ADS-B -> NMEAConverter

### ISSUE THREAD

**Issue by CyberLab85** [RooieDirk/NmeaConverter_pi#3]
Hi,

I'm interesting in ADS-B to NMEA convert to see planes on Open CPN as for example SAR or any new icon for them. ¿can you build it?

Thansk

**Comment by rgleason** [comment]
http://www.ads-b.com/
This isn't a part of the marine navigation mission.

**Comment by rgleason** [comment]
You if you can get a data stream with ADS-B, go ahead and record it as a nmea serial stream (text file).
Then you can try playing it in Opencpn with VDR_pi or VDRplayer and you will see that stream in the Nmea Debug Window. 

Opencpn will not show thee ADS-B instances however. You will then need to convert those ADS-B instances into somethiing else that Opencpn does recognize with NmeaConverter.

It will work, but you'll have to find an object that makes sense as an airplane and acts appropriately.

**Comment by RooieDirk** [comment]
No plans to do anything beyond plain NMEA.
