### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by Rasbats** [RooieDirk/NmeaConverter_pi#4]
Gave this a look but no solution.
I made some progress by using != wxNOT_FOUND instead of '>=0" in the following functions:

```
void nmeaSendObj::SetFormatString(wxString FormatStr)
{
    if( FormatStr == wxEmptyString )
        FormatStr = wxT("$DummyFormat"); 
    FormatString=FormatStr;   
    //find needed Variables
    NeededVariables = FindStartWithDollarSubSets( FormatStr, VarAlphaDigit);
    //find needed Sentences
    NeededSentences.Clear();
    unsigned int i = 0;    
    while ( i < NeededVariables.Count() )
    {
        unsigned int j = 0;
		while (((VarAlpha.Find(NeededVariables[i].Mid(j, 1)) != wxNOT_FOUND)) &&


wxArrayString nmeaSendObj::FindStartWithDollarSubSets(wxString FormatStr, wxString AllowdCharStr)
{  //Find pieces of text starting with'$' wich are the variables used
    int startpos=2;
    wxArrayString ReturnArray;
    if (FormatStr.Length() > 4)
    {
		while (FormatStr.find(wxT("$"), startpos) != wxNOT_FOUND)

```
But then the whole thing froze when it tried to make the NMEA output. Where it says "output sentence comes here" nothing appeared.

Do you have code from another version that compiles on Windows to compare with? Later than 0.2.

Regards,
Mike

**Comment by rgleason** [comment]
Mike, I git fetched Pavel's version and the current head compiles and seems to work on windows.

![screenshot 263](https://user-images.githubusercontent.com/2363959/37734640-28bd4532-2d22-11e8-8281-9be823a48da8.png)

You ask good questions.  Now that they are divergent, how do you fix that? Make a PR of Pavel's somehow and send it to RooieDirk to merge?

**Comment by rgleason** [comment]
Comparing with notepad++ there are some real differences in nmeaconverter_pi.cpp  at the following lines:
102
109-112
198
241
273-273
280-285
296-311
317-343
359-392


152
158-171

**Comment by rgleason** [comment]
Maybe RooieDirks recent commits could be applies to Pavel's repository?

**Comment by rgleason** [comment]
This version runs in windows. (I am stepping forward  by git checkout hash, then  compile)

Commits on Feb 8, 2016
    correct number of decimals in output
    
98d3a83

**Comment by rgleason** [comment]
Runs in windows  Commits on Feb 17, 2016
    Update NmeaConverter_pi.cpp    3d6d458

**Comment by rgleason** [comment]
Runs in Windows
Commits on Feb 28, 2018    
Correct double entry's when reopening dialog  44bfb48
![screenshot 264](https://user-images.githubusercontent.com/2363959/37739248-ed301108-2d2f-11e8-95bd-0dfda6b42195.png)

**Comment by rgleason** [comment]
This one also works with windows, does not stop after hit "New"
![screenshot 265](https://user-images.githubusercontent.com/2363959/37739519-b58ae736-2d30-11e8-8b2c-49cb5d56739f.png)

Commits on Mar 12, 2018
Add wildcards  a017ec1

nmeaconverter_pi-0.9

**Comment by rgleason** [comment]
I then checked out master and compiled that. It processed but when installed I could not start opencpn because  nmeaconverter_pi was set to "1" or "enable" in the opencpn.ini.  I changed that to "0" in the ini file and Opencpn loaded.  Then I tried to "enable" the plugin and it failed Opencpn immediately. 

C:\Users\Frederick\Documents\GitHub\NmeaConverter_pi\build>git branch -va
* master                  e686766 fix a few compiler warnings
  remotes/origin/master   e686766 fix a few compiler warnings
  remotes/upstream/master e686766 fix a few compiler warnings

These results are a little different than my earlier compile of this commit but the results are the same. Opencpn failure.

I am sorry but some of the warning fixes must have derailed the plugin insofar as windows is concerned.

I am going to step back to the previous version until this can be fixed. Thanks. Rasbats for asking good questions.

**Comment by rgleason** [comment]
These are the nine warnings that were coming up at the "Add Wildcards" commit



```
Build succeeded.

"C:\Users\Frederick\Documents\GitHub\NmeaConverter_pi\build\ALL_BUILD.vcxproj"
(default target) (1) ->
"C:\Users\Frederick\Documents\GitHub\NmeaConverter_pi\build\nmeaconverter_pi.vc
xproj" (default target) (3) ->
(ClCompile target) ->
  C:\Users\Frederick\Documents\GitHub\NmeaConverter_pi\src\NmeaConverter_pi.cpp
(162): warning C4018: '<' : signed/unsigned mismatch [C:\Users\Frederick\Docume
nts\GitHub\NmeaConverter_pi\build\nmeaconverter_pi.vcxproj]
  C:\Users\Frederick\Documents\GitHub\NmeaConverter_pi\src\NmeaConverter_pi.cpp
(298): warning C4018: '<' : signed/unsigned mismatch [C:\Users\Frederick\Docume
nts\GitHub\NmeaConverter_pi\build\nmeaconverter_pi.vcxproj]
  C:\Users\Frederick\Documents\GitHub\NmeaConverter_pi\src\NmeaConverter_pi.cpp
(302): warning C4018: '<' : signed/unsigned mismatch [C:\Users\Frederick\Docume
nts\GitHub\NmeaConverter_pi\build\nmeaconverter_pi.vcxproj]
  C:\Users\Frederick\Documents\GitHub\NmeaConverter_pi\src\NmeaConverter_pi.cpp
(360): warning C4018: '<' : signed/unsigned mismatch [C:\Users\Frederick\Docume
nts\GitHub\NmeaConverter_pi\build\nmeaconverter_pi.vcxproj]


"C:\Users\Frederick\Documents\GitHub\NmeaConverter_pi\build\ALL_BUILD.vcxproj"
(default target) (1) ->
"C:\Users\Frederick\Documents\GitHub\NmeaConverter_pi\build\nmeaconverter_pi.vc
xproj" (default target) (3) ->
(Link target) ->
  NmeaConverter_pi.obj : warning LNK4217: locally defined symbol ??0wxEcEngine@
@QAE@XZ (public: __thiscall wxEcEngine::wxEcEngine(void)) imported in function
"public: void __thiscall nmeaSendObj::ComputeOutputSentence(void)" (?ComputeOut
putSentence@nmeaSendObj@@QAEXXZ) [C:\Users\Frederick\Documents\GitHub\NmeaConve
rter_pi\build\nmeaconverter_pi.vcxproj]
  NmeaConverter_pi.obj : warning LNK4217: locally defined symbol ??1wxEcEngine@
@QAE@XZ (public: __thiscall wxEcEngine::~wxEcEngine(void)) imported in function
 "public: void __thiscall nmeaSendObj::ComputeOutputSentence(void)" (?ComputeOu
tputSentence@nmeaSendObj@@QAEXXZ) [C:\Users\Frederick\Documents\GitHub\NmeaConv
erter_pi\build\nmeaconverter_pi.vcxproj]
  NmeaConverter_pi.obj : warning LNK4217: locally defined symbol ?GetLastError@
wxEcEngine@@QAEHXZ (public: int __thiscall wxEcEngine::GetLastError(void)) impo
rted in function "public: void __thiscall nmeaSendObj::ComputeOutputSentence(vo
id)" (?ComputeOutputSentence@nmeaSendObj@@QAEXXZ) [C:\Users\Frederick\Documents
\GitHub\NmeaConverter_pi\build\nmeaconverter_pi.vcxproj]
  NmeaConverter_pi.obj : warning LNK4217: locally defined symbol ?Compute@wxEcE
ngine@@QAENXZ (public: double __thiscall wxEcEngine::Compute(void)) imported in
 function "public: void __thiscall nmeaSendObj::ComputeOutputSentence(void)" (?
ComputeOutputSentence@nmeaSendObj@@QAEXXZ) [C:\Users\Frederick\Documents\GitHub
\NmeaConverter_pi\build\nmeaconverter_pi.vcxproj]
  NmeaConverter_pi.obj : warning LNK4217: locally defined symbol ?SetFormula@wx
EcEngine@@QAE_NVwxString@@@Z (public: bool __thiscall wxEcEngine::SetFormula(cl
ass wxString)) imported in function "public: void __thiscall nmeaSendObj::Compu
teOutputSentence(void)" (?ComputeOutputSentence@nmeaSendObj@@QAEXXZ) [C:\Users\
Frederick\Documents\GitHub\NmeaConverter_pi\build\nmeaconverter_pi.vcxproj]

    9 Warning(s)
    0 Error(s)
```

**Comment by rgleason** [comment]
I put the earlier commit  "Add Wildcards" out for download and Beta testing, because the current master is not working.

**Comment by RooieDirk** [comment]
Something goes wrong;-( it must be the wildcard code that's going bad, although it worked here before I made the update here. Althoug I have to admit I only tested it in my development system witch runs a portable version of O.
The coming week I don't have time to dive into it. But it is likely to be in the part of code that is testing if a substring is valid before make a substitute by a value

**Comment by rgleason** [comment]
Dirk. The "Add Wildcards" version compiles and makes an executable. I can install it and make formulas. I just have not tested if they work yet.  So this  Commit from 10 days ago seems to be working.
Commits on Mar 12, 2018
    Add wildcards
    @RooieDirk
    RooieDirk committed 10 days ago   a017ec1
I have put this out for Beta download  and testing and posted it in the CF Thread 
http://www.cruisersforum.com/forums/f134/compass-deviation-plugin-future-requests-187912.html#post2601253

It appears that something in the next commit is causing trouble.

**Comment by rgleason** [comment]
Figured this out. Closing
